export const SIGNUP_WITH_EMAIL_REQUEST: string = "SIGNUP_WITH_EMAIL_REQUEST";
export const SIGNUP_WITH_EMAIL_SUCCESS: string = "SIGNUP_WITH_EMAIL_SUCCESS";
export const SIGNUP_WITH_EMAIL_FAILURE: string = "SIGNUP_WITH_EMAIL_FAILURE";
